# Generated by Django 4.2.1 on 2023-08-08 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0004_alter_trip_change_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='chkIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 11, 52, 328764)),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 23, 11, 52, 328764)),
        ),
    ]
