# Generated by Django 4.2.1 on 2023-09-01 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0045_tripdetail_budget_tripdetail_date_tripdetail_no_sch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 21, 48, 16, 971687)),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 21, 48, 16, 972679)),
        ),
        migrations.AlterField(
            model_name='tripdetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
