# Generated by Django 4.2.1 on 2023-09-02 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0051_remove_trip_change_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 2, 15, 48, 49, 231638), null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 9, 2, 15, 48, 49, 231638), null=True),
        ),
    ]
