# Generated by Django 4.2.1 on 2023-09-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0053_remove_trip_date_end_remove_trip_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
