# Generated by Django 4.2.1 on 2023-09-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0055_tripclone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripClone',
        ),
    ]
