# Generated by Django 4.2.1 on 2023-09-10 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0057_tripclone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripclone',
            name='date',
        ),
        migrations.AddField(
            model_name='tripclone',
            name='date_create',
            field=models.DateField(auto_created=True, blank=True, default=datetime.datetime(2023, 9, 10, 22, 41, 51, 483625), null=True),
        ),
        migrations.AlterModelTable(
            name='tripclone',
            table='TripClone',
        ),
    ]
