# Generated by Django 4.2.1 on 2023-09-19 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0059_alter_tripclone_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tripdetail',
            name='no_sch',
        ),
        migrations.AlterField(
            model_name='tripclone',
            name='date_create',
            field=models.DateField(auto_created=True, blank=True, default=datetime.datetime(2023, 9, 19, 21, 58, 13, 439750), null=True),
        ),
    ]
