# Generated by Django 4.2.1 on 2023-09-19 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0060_remove_tripdetail_budget_remove_tripdetail_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripclone',
            name='date_create',
            field=models.DateField(auto_created=True, blank=True, default=datetime.datetime(2023, 9, 20, 6, 11, 7, 161688), null=True),
        ),
        migrations.AlterField(
            model_name='tripclone',
            name='tripClone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tripClone', to='trip_app.trip'),
        ),
        migrations.AlterField(
            model_name='tripclone',
            name='tripMain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tripMain', to='trip_app.trip'),
        ),
    ]
