# Generated by Django 4.2.1 on 2023-09-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0084_alter_payment_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='change_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
