# Generated by Django 4.2.1 on 2023-07-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplace',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
