# Generated by Django 4.2.1 on 2023-07-16 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0002_alter_businessplace_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 20, 7, 54, 807168)),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='timeClose',
            field=models.TimeField(default=datetime.datetime(2023, 7, 16, 20, 7, 54, 807168)),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='timeOpen',
            field=models.TimeField(default=datetime.datetime(2023, 7, 16, 20, 7, 54, 807168)),
        ),
    ]
