# Generated by Django 4.2.1 on 2023-07-16 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0003_alter_businessplace_change_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detaill', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 20, 15, 25, 610097)),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='timeClose',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='timeOpen',
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name='businessplace',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type_business_place', to='businessplace_app.businesstype'),
            preserve_default=False,
        ),
    ]
