# Generated by Django 4.2.1 on 2023-07-16 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0004_businesstype_alter_businessplace_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 22, 21, 5, 951982)),
        ),
        migrations.CreateModel(
            name='BusinessPlacePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('detaill', models.TextField()),
                ('link', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('change_datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 16, 22, 21, 5, 953460))),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_business_place', to='businessplace_app.businessplace')),
            ],
        ),
    ]
