# Generated by Django 4.2.1 on 2023-07-17 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0006_businessplace_place_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessplace',
            name='place_user',
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 9, 10, 25, 992211)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 9, 10, 25, 993208)),
        ),
    ]
