# Generated by Django 4.2.1 on 2023-07-17 03:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businessplace_app', '0010_alter_businessplace_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 34, 54, 336995)),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='place_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 10, 34, 54, 338453)),
        ),
    ]
