# Generated by Django 4.2.1 on 2023-07-17 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0020_alter_businessplace_change_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplacepicture',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 11, 50, 18, 391473)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 11, 50, 18, 392442)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
