# Generated by Django 4.2.1 on 2023-07-17 04:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0021_businessplacepicture_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 11, 56, 25, 354324)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 11, 56, 25, 355322)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('change_datetime', models.DateTimeField(default=datetime.datetime(2023, 7, 17, 11, 56, 25, 356318))),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vr_business_place', to='businessplace_app.businessplace')),
            ],
        ),
    ]
