# Generated by Django 4.2.1 on 2023-07-17 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0029_alter_businessplace_change_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplace',
            name='pic_link1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessplace',
            name='pic_link2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessplace',
            name='pic_link3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 17, 30, 4, 42113)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 17, 30, 4, 43171)),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 17, 30, 4, 44199)),
        ),
    ]
