# Generated by Django 4.2.1 on 2023-07-17 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0030_businessplace_pic_link1_businessplace_pic_link2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplace',
            name='district',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessplace',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 22, 28, 26, 804197)),
        ),
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 22, 28, 26, 804197)),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 22, 28, 26, 805639)),
        ),
    ]
