# Generated by Django 4.2.1 on 2023-08-30 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0073_alter_businessplacepicture_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 21, 26, 0, 831523)),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 21, 26, 0, 832520)),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 21, 26, 0, 832520)),
        ),
        migrations.AlterModelTable(
            name='businessplacepicture',
            table='BusinessPlacePicture',
        ),
        migrations.AlterModelTable(
            name='ratingandcomment',
            table='RatingAndComment',
        ),
    ]
