# Generated by Django 4.2.1 on 2023-08-30 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0074_alter_businessplacepicture_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 10, 20, 812170)),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 10, 20, 813203)),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 10, 20, 813203)),
        ),
        migrations.AlterModelTable(
            name='businessplace',
            table=None,
        ),
        migrations.AlterModelTable(
            name='businessplacepicture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='businesstype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ratingandcomment',
            table=None,
        ),
    ]
