# Generated by Django 4.2.1 on 2023-08-30 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0075_alter_businessplacepicture_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 20, 35, 667855)),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 20, 35, 668851)),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 0, 20, 35, 668851)),
        ),
        migrations.AlterModelTable(
            name='businessplacepicture',
            table='BusinessPlacePicture',
        ),
        migrations.AlterModelTable(
            name='businesstype',
            table='BusinessType',
        ),
        migrations.AlterModelTable(
            name='ratingandcomment',
            table='RatingAndComment',
        ),
    ]
