# Generated by Django 4.2.1 on 2023-09-08 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0102_alter_businessplacepicture_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 19, 33, 24, 707819)),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='change_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 19, 33, 24, 708816), null=True),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 8, 19, 33, 24, 708816), null=True),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 19, 33, 24, 708816)),
        ),
    ]
