# Generated by Django 4.2.1 on 2023-09-11 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessplace_app', '0108_alter_businessplacepicture_change_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplacepicture',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 21, 12, 16, 140037)),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='change_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 11, 21, 12, 16, 141061), null=True),
        ),
        migrations.AlterField(
            model_name='ratingandcomment',
            name='created_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 11, 21, 12, 16, 141061), null=True),
        ),
        migrations.AlterField(
            model_name='virtualtour',
            name='change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 21, 12, 16, 140037)),
        ),
    ]
